version: '2'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - /var/lib/myvolume
    #redis:
      #image: "redis:alpine"
  
  business:
    build: ./business
    ports:
      - "42022:22"
    #networks: 
      - web
      - config
      - ssh
    volumes:
      - /var/lib/myvolume   
  
  configs:
    build: ./configs
    volumes:
      - /var/lib/myvolume    
    ports:
      - "8001:5432" 

  ssh:
    build: ./ssh
    ports:
      - "42022:22"
    networks: 
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: "2001:3984:3989::10"
    volumes:
      - /var/lib/myvolume
    
volumes:
  mydata:

networks:
  default:
    driver: custom-driver-1
  
  #web:
  #config:
  #ssh:

  app_net:
  driver: bridge
  #enable_ipv6: true
  ipam:
    driver: default
    config:
    - subnet: 172.16.238.0/24
      gateway: 172.16.238.1
    - subnet: 2001:3984:3989::/64
      gateway: 2001:3984:3989::1
