version: '2'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - type: "volume"
        source: mydata
        target: /data
    #redis:
      #image: "redis:alpine"
  
  business:
    build: ./business
    ports: 
      - "42022:22"
    networks: 
      - web
      - config
      - ssh
  
  configs:
    build: ./configs
  
  ssh:
    build: /ssh
    ports:
      - "42022:22"
    networks: 
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: "2001:3984:3989::10"
    
volumes:
  mydata:

networks:
  app_net:
    driver: bridge
    #enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
