version: '2'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - myvolume:/var/lib/myvolume
  redis:
    container_name: redis_store
    image: armhf/redis
  
  business:
    build: ./business
    privileged: true
    ports:
     - "22:22"
    #networks: 
    #  - web
    #  - config
    #  - ssh
    networks: 
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: "2001:3984:3989::10"
    volumes:
      - myvolume:/var/lib/myvolume   
  
  configs:
    build: ./configs
    volumes:
      - myvolume:/var/lib/myvolume   
    ports:
      - "8080:8080" 

  ssh:
    build: ./ssh
    privileged: true
    ports:
      - "42022:22"
    networks: 
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: "2001:3984:3989::10"

volumes:
  myvolume:
    driver: local

networks:
  default:
    driver: custom-driver-1
  
  #web:
  #config:
  #ssh:

  app_net:
    driver: bridge
  #enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: "2001:3984:3989::/64"
        gateway: "2001:3984:3989::1"
