version: '2'
services:
  web:
    build: ./web
    ports:
      - 8080:8080
    volumes:
      - myvolume:/var/lib/myvolume
  redis:
    container_name: redis_store
    image: armhf/redis
  
  business:
    build: ./business
    privileged: true
    ports:
     - 22
    #networks: 
    #  - web
    #  - config
    #  - ssh
    networks: 
      app_net:
        ipv4_address: 192.168.1.102
        ipv6_address: 2001:3984:3989::102
    volumes:
      - myvolume:/var/lib/myvolume   
  
  configs:
    build: ./configs
    volumes:
      - myvolume:/var/lib/myvolume   
    ports:
      - 8000:8000
    networks: 
      - app_net 

  ssh:
    build: ./ssh
    privileged: true
    ports:
      - 22:4038
    networks: 
      app_net:
        ipv4_address: 192.168.1.103
        ipv6_address: "2001:3984:3989::103"

volumes:
  myvolume:
    driver: local

networks:
  default:
    driver: custom-driver-1
  
  #web:
  #config:
  #ssh:

  app_net:
    driver: bridge
  #enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 198.168.1.5/120
        gateway: 192.168.1.6
      #- subnet: "2001:3984:3989::/64"
      #- gateway: "2001:3984:3989::1"
      ############
